api_weather = "YOUR_WEATHER_API_KEY"             # The api Key from openweathermap.org
weather_location = "Munich"                      # Location can be city, state; city, country; zip code. (this is for the weather)
birthday = "Name:dd.mm."                         # Your Birthday, so Vector can congratulate you
temperature = "metric"                           # Enter "imperial" or "metric"
news_count = 3                                   # How many news stories Vector should read (max is 7 to 9)
news_feed = "YOUR_NEWS_FEED"                     # You can use any rss feed for this
mail_imap = "imap.gmail.com"                     # or use some other imap server
mail_account = "YOUR_E_MAIL"                     # the email address that is checked
mail_pw = "YOUR_E_MAIL_PASSWORD"                 # the mail password
mqtt_broker_ip = "YOUR_MQTT_BROKER_IP"           # IP of your MQTT Broker
mqtt_user = "YOUR_MQTT_USER"                     # your MQTT user
mqtt_pw = "YOUR_MQTT_PW"                         # your MQTT password
